custom:
  protocol: http
  client-host : localhost
  server-host : localhost
  client-port : 5173
  server-port : 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_image, profile_nickname, account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salmon?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${LOCAL_DB_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:sunny-wavelet-429609-t9-5d820b98637e.json
        project-id: sunny-wavelet-429609-t9-5d820b98637e
        bucket: fromnow-bucket

google:
  cloud:
    credentials:
      path: sunny-wavelet-429609-t9-5d820b98637e.json

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

springdoc:
  packages-to-scan: com.knu.salmon
  override-with-generic-response: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha